from . import sale_order
from . import orvea_city
from . import res_partner
from . import product_template
from . import prestation_list
from . import avenant_ccp
from . import clause_report
from . import contract_report
from . import avenant_report
from . import order_report
from . import maitre_ouvrage
from . import lot_type
from . import general_report
